"""Add emergency contact table

Revision ID: 628a356d5bf8
Revises: 57b643e19829
Create Date: 2025-08-08 22:47:21.407601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628a356d5bf8'
down_revision = '57b643e19829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_contact')
    # ### end Alembic commands ###
